// <auto-generated />
namespace Infraestrutura.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Primeiras_entidades : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Primeiras_entidades));
        
        string IMigrationMetadata.Id
        {
            get { return "201708300252353_Primeiras_entidades"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
